version: '3.8'
services:
  testmysql:
    container_name: mysql
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: testmysql
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql:rw
    ports:
      - "3300:3306"
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

#  webflux-102:
#    image: jwoo5264/webflux-102:latest
#    container_name: webflux-102
#    environment:
#      TZ: Asia/Seoul
#      SPRING_DATASOURCE_URL: r2dbc:pool:mysql://localhost:3306/testmysql
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 1234
#    restart: always
#    ports:
#      - "8080:8080"
