#server:
#  port: 8080
#  ssl:
#    enabled: true
#    key-store-password: web123456
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/testmysql
    username: root
    password: 1234

logging:
  level:
    org.springframework.r2dbc.core: debug